# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Permission/~create/$",
        view=views.PermissionCreateView.as_view(),
        name='Permission_create',
    ),
    url(
        regex="^Permission/(?P<pk>\d+)/~delete/$",
        view=views.PermissionDeleteView.as_view(),
        name='Permission_delete',
    ),
    url(
        regex="^Permission/(?P<pk>\d+)/$",
        view=views.PermissionDetailView.as_view(),
        name='Permission_detail',
    ),
    url(
        regex="^Permission/(?P<pk>\d+)/~update/$",
        view=views.PermissionUpdateView.as_view(),
        name='Permission_update',
    ),
    url(
        regex="^Permission/$",
        view=views.PermissionListView.as_view(),
        name='Permission_list',
    ),
	url(
        regex="^ModelPermission/~create/$",
        view=views.ModelPermissionCreateView.as_view(),
        name='ModelPermission_create',
    ),
    url(
        regex="^ModelPermission/(?P<pk>\d+)/~delete/$",
        view=views.ModelPermissionDeleteView.as_view(),
        name='ModelPermission_delete',
    ),
    url(
        regex="^ModelPermission/(?P<pk>\d+)/$",
        view=views.ModelPermissionDetailView.as_view(),
        name='ModelPermission_detail',
    ),
    url(
        regex="^ModelPermission/(?P<pk>\d+)/~update/$",
        view=views.ModelPermissionUpdateView.as_view(),
        name='ModelPermission_update',
    ),
    url(
        regex="^ModelPermission/$",
        view=views.ModelPermissionListView.as_view(),
        name='ModelPermission_list',
    ),
	url(
        regex="^FieldPermission/~create/$",
        view=views.FieldPermissionCreateView.as_view(),
        name='FieldPermission_create',
    ),
    url(
        regex="^FieldPermission/(?P<pk>\d+)/~delete/$",
        view=views.FieldPermissionDeleteView.as_view(),
        name='FieldPermission_delete',
    ),
    url(
        regex="^FieldPermission/(?P<pk>\d+)/$",
        view=views.FieldPermissionDetailView.as_view(),
        name='FieldPermission_detail',
    ),
    url(
        regex="^FieldPermission/(?P<pk>\d+)/~update/$",
        view=views.FieldPermissionUpdateView.as_view(),
        name='FieldPermission_update',
    ),
    url(
        regex="^FieldPermission/$",
        view=views.FieldPermissionListView.as_view(),
        name='FieldPermission_list',
    ),
	url(
        regex="^SlugPermission/~create/$",
        view=views.SlugPermissionCreateView.as_view(),
        name='SlugPermission_create',
    ),
    url(
        regex="^SlugPermission/(?P<pk>\d+)/~delete/$",
        view=views.SlugPermissionDeleteView.as_view(),
        name='SlugPermission_delete',
    ),
    url(
        regex="^SlugPermission/(?P<pk>\d+)/$",
        view=views.SlugPermissionDetailView.as_view(),
        name='SlugPermission_detail',
    ),
    url(
        regex="^SlugPermission/(?P<pk>\d+)/~update/$",
        view=views.SlugPermissionUpdateView.as_view(),
        name='SlugPermission_update',
    ),
    url(
        regex="^SlugPermission/$",
        view=views.SlugPermissionListView.as_view(),
        name='SlugPermission_list',
    ),
	]
